version: '3'

services:
  web:
    build: .
    command: hanami server --host=0.0.0.0
    ports:
      - 2300:2300
    volumes:
      - $PWD:/app
    depends_on:
      - db
    environment:
      HANAMI_ENV: development

  db:
    image: postgres:12.3-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
